apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: default
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 5000  # your app runs on 5000
