version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing Git...
      - apt-get update && apt-get install -y git
  pre_build:
    commands:
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - echo "Build number: $IMAGE_TAG"
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - git config --global user.email "pipeline@aws.com"
      - git config --global user.name "AWS CodePipeline"
      - echo Cloning main branch...
      - git clone --branch main https://github.com/${APP_REPO}.git app-main
      - cd app-main
  build:
    commands:
      - echo Building and pushing Docker image...
      - docker build -t $DOCKERHUB_USERNAME/aws-lab:$IMAGE_TAG .
      - docker push $DOCKERHUB_USERNAME/aws-lab:$IMAGE_TAG
  post_build:
    commands:
      - echo Cloning deploy branch...
      - cd ..
      - git clone --branch deploy https://$GITHUB_TOKEN@github.com/${APP_REPO}.git app-deploy
      - cd app-deploy
      - sed -i 's/^\([[:space:]]*tag:\).*/\1 "'"$IMAGE_TAG"'"/' helm/values.yaml
      - git add helm/values.yaml
      - git commit -m "Update image tag to $IMAGE_TAG"
      - git push origin deploy
artifacts:
  files: []
